name: oryx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.6
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.1.1
  # easy to integrate blocs and cubits into Flutter
  flutter_bloc: ^8.1.5
  # automatically persists and restores bloc and cubit states
  hydrated_bloc: ^9.1.5
  # exposes custom event transformers
  bloc_concurrency: ^0.2.5
  # Service locator
  get_it: ^8.0.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.3.2
  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.1.0
  # simplify form representation and validation in a generic way.
  formz: ^0.7.0
  # finding commonly used locations on the filesystem
  path_provider: ^2.1.4
  # check for an Active Internet connection
  internet_connection_checker: ^1.0.0+1
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0
  # A powerful HTTP networking package for Dart/Flutter
  dio: ^5.7.0
  # Annotations for freezed
  freezed_annotation: 2.4.4
  # automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0
  # A clean and lightweight loading widget for Flutter, Easy to use without context
  flutter_easyloading: ^3.0.5
  # Customize Flutter's default white native splash screen with background color and splash image.
  flutter_native_splash: ^2.4.1
  # Draw SVG files using Flutter
  flutter_svg: ^2.0.9
  # to show images from the internet and keep them in the cache directory
  cached_network_image: ^3.4.1
  # provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # Generating copyWith extensions for classes
  copy_with_extension: ^5.0.3
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.1
  # A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
  flutter_slidable: ^3.1.1
  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.0.7
  # A Flutter plugin for Android, iOS and Web supports cropping images
  image_cropper: ^8.0.2
  # A simple widget for full screen with swipe to dismiss, pinch & zoom.
  insta_image_viewer: ^1.0.4
  # Utilities for handling media (MIME) types, including determining a type from a file extension and file contents.
  mime: ^1.0.6
  # RFC4122 (v1, v4, v5, v6, v7, v8) UUID Generator and Parser for Dart
  uuid: ^4.5.1
  # Flutter plugin for accessing information about the battery state(full, charging, discharging).
  battery_plus: ^6.1.0
  # easy access to platform specific location services
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/images/splash.png"

  android_12:
    image: "assets/images/splash_icon.png"
    color: "#ffffff"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
